### ISSUE TITLE
ValueError: Range cannot be empty (low >= high) unless no samples are taken in dataset.py

### ISSUE THREAD

**Issue by kgarg8** [parkseobin/MLSR#4]
Hi Seobin Park/ Jinsu Yoo,

Thanks for releasing the code.

A very quick question for you... In the following code,
https://github.com/parkseobin/MLSR/blob/282074bf304a81fe90114d5d8197d72c9ee4b185/dataset.py#L117

both ```maml_hr_img.size[0]``` and ```self.patch_size``` are 512 and thus randint(0) throws ValueError. Did you mean to perform some other operation?
               
Attacking the stack trace for more reference:                                                                                                                                             
```
Exception in thread Thread-1:                                                                                                                               
Traceback (most recent call last):                                                                                                                          
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/threading.py", line 926, in _bootstrap_inner                                                         
    self.run()                                                                                                                                              
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/threading.py", line 870, in run                                                                      
    self._target(*self._args, **self._kwargs)                                                                                                               
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 52, in enqueue_thread                                                                          
    = self.next(test=False)                                                                                                                                 
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 120, in next                                                                                   
    return self.next(test)                                                                                                                                  
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 120, in next                                                                                   
    return self.next(test)                                                                                                                                  
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 120, in next                                                                                   
    return self.next(test)                                                                                                                                  
  [Previous line repeated 33 more times]                                                                                                                    
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 123, in next                                                                                   
    left = np.random.randint(maml_hr_img.size[0] - self.patch_size)                                                                                         
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint                                                                                                
ValueError: Range cannot be empty (low >= high) unless no samples are taken 
```

Thanks,
Krishna

**Comment by parkseobin** [comment]
I made a quick fix for the problem you raised. 

Thanks for your feedback!

**Comment by kgarg8** [comment]
Thanks Seobin for the quick fix. However, this doesn't fix the code completely.
Now, it gives the RecursionError on the line:

https://github.com/parkseobin/MLSR/blob/542758fc0c884fe7c0b014006773d01a7d2d60fe/dataset.py#L115

Here's the stacktrace for it:

```
  File "main.py", line 33, in <module>
    trainer.train()
  File "/home/kgarg8/kgarg8-workspace/MLSR/train.py", line 176, in train
    self.dataset.enqueue_thread(sess)
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 53, in enqueue_thread
    = self.next(test=False)
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 121, in next
    return self.next(test)
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 121, in next
    return self.next(test)
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 121, in next
    return self.next(test)
  [Previous line repeated 984 more times]
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 117, in next
    maml_hr_img = self.choose_random_image(test)
  File "/home/kgarg8/kgarg8-workspace/MLSR/dataset.py", line 104, in choose_random_image
    random_img = Image.open(random_img).convert('RGB')
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/Image.py", line 2690, in open
    im = _open_core(fp, filename, prefix)
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/Image.py", line 2676, in _open_core
    im = factory(fp, filename)
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/ImageFile.py", line 103, in __init__
    self._open()
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 582, in _open
    s = self.png.call(cid, pos, length)
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 147, in call
    return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 347, in chunk_IHDR
    s = ImageFile._safe_read(self.fp, length)
  File "/home/kgarg8/anaconda3/envs/MLSR/lib/python3.7/site-packages/PIL/ImageFile.py", line 538, in _safe_read
    if size <= 0:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by parkseobin** [comment]
If all the images in your train dataset are smaller than 512, you should alter the patch size accordingly via `--patch-size` flag.
Have you checked the sizes?

**Comment by kgarg8** [comment]
Thanks for the support, altering patch-size works.
